version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  ignore:
    # TODO: Remove me when https://github.com/Shopify/shipit-engine/pull/1314 is resolved
    - dependency-name: "omniauth-github"
