services:
  db: 
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: shipit
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - '3306:3306'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

volumes:
  db_data: {}