apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    server: https://kubernetes.default.svc.cluster.local
  name: rubygems
contexts:
- context:
    cluster: rubygems
    user: shipit
  name: rubygems
users:
- name: shipit
  user:
    tokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
